name: Daily Python Jobs

on:
  schedule:
    - cron: "0 15 * * *"   # roda todo dia Ã s 15:00 UTC (~12:00 no Brasil)
  workflow_dispatch:       # permite rodar manualmente tambÃ©m

jobs:
  run-daily-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run first script
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python src/data/download.py

      - name: Run second script
        run: |
          python src/strategy/process_data.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "LucasHonoratoDeSouza"
          git config --global user.email "lucashonoratodesouza10@gmail.com"
          git add data/raw/*.json data/processed/*.json
          git commit -m "ðŸ¤– Daily Data Update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
